print ("\t Welcome to Mad Libs!")
print ("\t Please provide the following to help")
print ("\t create a new story")
Name = input('Enter a name:')
Plural = input('Enter a plural noun:')
Number = input('Enter an integer value:')
Body = input('Enter a a body part:')
Verb = input('Enter a verb:')
print ("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
print ("Here is your story")
print ("The famous explorer {0} had nearly given up a life long quest to find".format(Name))
print ("the lost city of {0} when one day, the {0} found the explorer.".format(Plural))
print ("Surrounded by {0} {1}, a tear came to {2}'s {3}.".format(Number,Plural,Name,Body))
print ("After all this time, the quest was finnaly over.")
print ("And then,the {0} promptly devoured {1}.".format(Plural,Name))
print ("The moral of the story? Be careful what you {0} for.".format(Verb))
print ("~~~~~~~~~~~~~~~~The end~~~~~~~~~~~~~~~~~~~~")